// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: b0a3abf5debe7461e388b512b82a4e0d71630a87d1fd1e991ef676b0b708b3b9

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "mts";

export const themeNames: ThemeName[] = ["mts"];

export type KcEnvName = "TERMS_AND_POLICY_URL" | "FORGOT_PASSOWRD";

export const kcEnvNames: KcEnvName[] = [
  "TERMS_AND_POLICY_URL",
  "FORGOT_PASSOWRD",
];

export const kcEnvDefaults: Record<KcEnvName, string> = {
  TERMS_AND_POLICY_URL: "https://gra-terms-and-policy-y98q.vercel.app/",
  FORGOT_PASSOWRD: "https://www.google.com/",
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext = import("./login/KcContext").KcContext;

declare global {
  interface Window {
    kcContext?: KcContext;
  }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
  const { kcContext, fallback } = props;
  return (
    <Suspense fallback={fallback}>
      {(() => {
        switch (kcContext.themeType) {
          case "login":
            return <KcLoginPage kcContext={kcContext} />;
        }
      })()}
    </Suspense>
  );
}
